# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Revolution' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

    pod 'Alamofire', '~> 5.2'
    pod 'RxSwift', '~> 5'
    pod 'RxCocoa', '~> 5'
    pod 'SnapKit', '~> 5.0.0'
    pod 'NSObject+Rx'
    pod 'MBProgressHUD', '~> 1.2.0'
    pod 'RxDataSources'
    pod 'YPImagePicker'
    pod 'Toast-Swift', '~> 5.0.1'
    pod 'PanModal'

  target 'RevolutionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RevolutionUITests' do
    # Pods for testing
  end

end
